//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tomin.TotalCmd.AzureBlob.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-8""?>
<ArrayOfBlobConfig xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance""
                        xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
     <BlobConfig>
             <StorageDisplayName>(Development)</StorageDisplayName>
             <AccountName />
             <AccountKey />
              <UseSsl>true</UseSsl>
              <UseDevelopmentStorage>true</UseDevelopmentStorage>
      </BlobConfig>
</ArrayOfBlobConfig>")]
        public global::System.Collections.Generic.List<Tomin.TotalCmd.AzureBlob.Configuration.BlobConfig> BlobConfigs {
            get {
                return ((global::System.Collections.Generic.List<Tomin.TotalCmd.AzureBlob.Configuration.BlobConfig>)(this["BlobConfigs"]));
            }
            set {
                this["BlobConfigs"] = value;
            }
        }
    }
}
